CREATE DATABASE IF NOT EXISTS wos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'wos'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON wos.* TO 'wos'@'%';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(10) NOT NULL,
    email VARCHAR(30) NOT NULL,
    gender VARCHAR(5),
    image_url VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);