CREATE DATABASE IF NOT EXISTS wos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'wos'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON wos.* TO 'wos'@'%';

FLUSH PRIVILEGES;
